# Generated by Django 4.2.24 on 2025-10-01 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='emodia.sports')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('emotion', models.CharField(choices=[('sad', '😰 우울'), ('tired', '🥱 지침'), ('anxious', '😰 불안'), ('angry', '😡 분노'), ('neutral', '😐 보통'), ('calm', '😌 차분'), ('excited', '🤩 설렘'), ('happy', '😊 행복')], max_length=20, verbose_name='감정 상태')),
                ('emotion_score', models.IntegerField(default=0, verbose_name='감정 점수')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('sports', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='emodia.sports', verbose_name='자동 매핑된 스포츠')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_records', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '감정 기록',
                'verbose_name_plural': '감정 기록들',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
