# Generated by Django 4.0 on 2025-09-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='감정을 기록한 날짜', verbose_name='날짜')),
                ('emotion', models.CharField(choices=[('happy', '😊 행복'), ('sad', '😰 우울'), ('angry', '😡 화남'), ('lonely', '😔 외로움'), ('excited', '😊 신남'), ('anxious', '🤗 불안'), ('calm', '😌 평온'), ('grateful', '🙏 감사')], max_length=20, verbose_name='감정 상태')),
                ('memo', models.TextField(blank=True, help_text='오늘 하루는 어땠나요? 간단한 힘들평을 남겨보세요...', null=True, verbose_name='감정 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_records', to='auth.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '감정 기록',
                'verbose_name_plural': '감정 기록들',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
