# Generated by Django 4.2.24 on 2025-10-04 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emodia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='운동 시간(초)')),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='emodia.sports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PoseFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(help_text='세션 시작 후 경과 시간(초)')),
                ('keypoints', models.JSONField(help_text='포즈 키포인트 좌표 데이터')),
                ('feedback', models.JSONField(blank=True, help_text='교정 피드백 데이터', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pose_frames', to='emodia.workoutsession')),
            ],
            options={
                'ordering': ['session', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('rule_based', '룰베이스'), ('random_forest', 'Random Forest'), ('neural_network', 'Neural Network'), ('hybrid', '하이브리드')], max_length=50)),
                ('version', models.CharField(help_text='모델 버전 (예: v1.0)', max_length=50)),
                ('model_file', models.FileField(help_text='저장된 모델 파일 (.pkl)', upload_to='ml_models/')),
                ('accuracy', models.FloatField(blank=True, help_text='정확도', null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(help_text='학습 데이터 수')),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('trained_by', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='현재 사용 중인 모델')),
                ('notes', models.TextField(blank=True, help_text='모델 설명 및 변경사항')),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='emodia.sports')),
            ],
            options={
                'verbose_name': 'ML 모델',
                'verbose_name_plural': 'ML 모델들',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='이 피드백이 도움이 되었나요?')),
                ('accuracy_rating', models.IntegerField(blank=True, help_text='피드백 정확도 (1-5)', null=True)),
                ('comment', models.TextField(blank=True, help_text='추가 의견')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pose_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='emodia.poseframe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '피드백 평가',
                'verbose_name_plural': '피드백 평가들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertPoseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_phase', models.CharField(choices=[('start', '시작'), ('middle', '중간'), ('peak', '정점'), ('end', '종료')], help_text='운동 단계', max_length=20)),
                ('quality_level', models.CharField(choices=[('perfect', '완벽'), ('good', '좋음'), ('acceptable', '수용 가능'), ('warning', '경고')], help_text='자세 품질', max_length=20)),
                ('keypoints', models.JSONField(help_text='정답 포즈 좌표')),
                ('description', models.TextField(help_text='자세 설명 (예: 목을 왼쪽으로 30도 기울인 상태)')),
                ('created_by', models.CharField(help_text='전문가 이름', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='ML 학습에 사용 여부')),
                ('features', models.JSONField(blank=True, help_text='추출된 특징 벡터', null=True)),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_templates', to='emodia.sports')),
            ],
            options={
                'verbose_name': '전문가 자세 템플릿',
                'verbose_name_plural': '전문가 자세 템플릿들',
                'ordering': ['sports', 'exercise_phase', 'quality_level'],
            },
        ),
    ]
