# Generated by Django 4.2.24 on 2025-10-03 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emodia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='운동 시간(초)')),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='emodia.sports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PoseFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(help_text='세션 시작 후 경과 시간(초)')),
                ('keypoints', models.JSONField(help_text='포즈 키포인트 좌표 데이터')),
                ('feedback', models.JSONField(blank=True, help_text='교정 피드백 데이터', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pose_frames', to='emodia.workoutsession')),
            ],
            options={
                'ordering': ['session', 'timestamp'],
            },
        ),
    ]
