# Generated by Django 4.2.24 on 2025-09-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionrecord',
            name='sports',
            field=models.IntegerField(blank=True, choices=[(1, '목풀기'), (2, '헬스'), (3, '축구'), (4, '농구'), (5, '수영')], help_text='오늘 한 운동교정', null=True, verbose_name='교정 기록'),
        ),
    ]
