# Generated by Django 4.2.24 on 2025-10-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodia', '0002_workoutsession_poseframe_mlmodel_feedbackrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionrecord',
            name='intensity',
            field=models.IntegerField(blank=True, default=50, null=True, verbose_name='감정 강도'),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='mood_after',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='운동 후 기분'),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='태그'),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='voice_of_mind',
            field=models.TextField(blank=True, null=True, verbose_name='마음의 소리'),
        ),
    ]
