# Generated by Django 4.2.24 on 2025-09-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodia', '0002_emotionrecord_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionrecord',
            name='emotion_score',
            field=models.IntegerField(default=0, verbose_name='감정 점수'),
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='emotion',
            field=models.CharField(choices=[('sad', '😰 우울'), ('tired', '🥱 지침'), ('anxious', '😰 불안'), ('angry', '😡 분노'), ('neutral', '😐 보통'), ('calm', '😌 차분'), ('excited', '🤩 설렘'), ('happy', '😊 행복')], max_length=20, verbose_name='감정 상태'),
        ),
    ]
