# Generated by Django 4.2.24 on 2025-10-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emodia', '0003_emotionrecord_intensity_emotionrecord_mood_after_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotionvideo',
            options={'ordering': ['difficulty', 'body_part', 'duration_minutes'], 'verbose_name': '운동 영상', 'verbose_name_plural': '운동 영상들'},
        ),
        migrations.AddField(
            model_name='emotionvideo',
            name='body_part',
            field=models.CharField(blank=True, choices=[('전신', '전신'), ('목', '목'), ('어깨', '어깨'), ('목어깨', '목어깨'), ('등', '등'), ('골반', '골반'), ('코어', '코어')], max_length=20, null=True, verbose_name='부위'),
        ),
        migrations.AddField(
            model_name='emotionvideo',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('초급', '초급'), ('중급', '중급'), ('고급', '고급'), ('자세교정', '자세교정')], max_length=20, null=True, verbose_name='난이도'),
        ),
        migrations.AddField(
            model_name='emotionvideo',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='시간(분)'),
        ),
        migrations.AddField(
            model_name='emotionvideo',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('스트레칭', '스트레칭'), ('요가', '요가'), ('필라테스', '필라테스'), ('운동', '운동'), ('이완스트레칭', '이완스트레칭'), ('통증완화스트레칭', '통증완화스트레칭'), ('모닝스트레칭', '모닝스트레칭'), ('오른쪽스트레칭', '오른쪽스트레칭'), ('왼쪽스트레칭', '왼쪽스트레칭')], max_length=50, null=True, verbose_name='운동 종류'),
        ),
        migrations.AddField(
            model_name='emotionvideo',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emotionvideo',
            name='sports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='emodia.sports'),
        ),
    ]
