# Generated by Django 4.2.24 on 2025-09-30 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emodia', '0003_emotionrecord_emotion_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='sports',
            field=models.IntegerField(blank=True, null=True, verbose_name='자동 매핑된 스포츠'),
        ),
        migrations.CreateModel(
            name='EmotionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='emodia.sports')),
            ],
        ),
    ]
