# Generated by Django 4.2.24 on 2025-09-29 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_goal', models.CharField(blank=True, choices=[('relax', '목, 어깨 뭉침 완화'), ('sleep', '수면의 질 개선'), ('stress', '스트레스 관리'), ('habit', '꾸준한 기록 습관 만들기'), ('energy', '에너지 회복')], max_length=50, null=True)),
                ('routine_time', models.TimeField(blank=True, help_text='루틴 알람 시간', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
