# Generated by Django 4.2.24 on 2025-10-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='routine_days',
            field=models.JSONField(blank=True, help_text='루틴 요일 목록', null=True),
        ),
    ]
